SELECT TOP (1000) [BatchID]
      ,[CustomerID]
      ,[UploadDate]
      ,[UploadBy]
      ,[Status]
      ,[TransCount]
      ,[TransTotal]
      ,[NextApprover]
      ,[PayProcess]
      ,[PayProcessRef]
      ,[Credit_Suspense]
      ,[Credit_Suspense_Date]
      ,[Credit_Suspense_Failed_Count]
      ,[Debit_Suspense]
      ,[Debit_Suspense_Date]
      ,[Debit_Suspense_Amount]
      ,[Debit_Suspense_Failed_Count]
      ,[Credit_Suspense_Amount]
  FROM [GAPS_DEV].[dbo].[AirTimeBatch] where BatchID=82623
